columns:
  - Age: int64
  - AnnualIncome: int64
  - CreditScore: int64
  - EmploymentStatus: category
  - EducationLevel: category
  - Experience: int64
  - LoanAmount: int64
  - LoanDuration: int64
  - MaritalStatus: category
  - NumberOfDependents: int64
  - HomeOwnershipStatus: category
  - MonthlyDebtPayments: int64
  - CreditCardUtilizationRate: float64
  - NumberOfOpenCreditLines: int64
  - NumberOfCreditInquiries: int64
  - DebtToIncomeRatio: float64
  - BankruptcyHistory: int64
  - LoanPurpose: category
  - PreviousLoanDefaults: int64
  - PaymentHistory: int64
  - LengthOfCreditHistory: int64
  - SavingsAccountBalance: int64
  - CheckingAccountBalance: int64
  - TotalAssets: int64
  - TotalLiabilities: int64 
  - MonthlyIncome: float64
  - UtilityBillsPaymentHistory: float64
  - JobTenure: int64
  - NetWorth: int64
  - BaseInterestRate: float64
  - InterestRate: float64
  - MonthlyLoanPayment: float64
  - TotalDebtToIncomeRatio: float64
  - LoanApproved: int64
  - RiskScore: float64


numerical_columns:
  - Age
  - AnnualIncome
  - CreditScore
  - Experience
  - LoanAmount
  - LoanDuration
  - NumberOfDependents
  - MonthlyDebtPayments
  - CreditCardUtilizationRate
  - NumberOfOpenCreditLines
  - NumberOfCreditInquiries
  - DebtToIncomeRatio
  - BankruptcyHistory
  - PreviousLoanDefaults
  - PaymentHistory
  - LengthOfCreditHistory
  - SavingsAccountBalance
  - CheckingAccountBalance
  - TotalAssets
  - TotalLiabilities
  - MonthlyIncome
  - UtilityBillsPaymentHistory
  - JobTenure
  - NetWorth
  - BaseInterestRate
  - InterestRate
  - MonthlyLoanPayment
  - TotalDebtToIncomeRatio



categrorical_columns:
  - EmploymentStatus
  - EducationLevel
  - MaritalStatus
  - HomeOwnershipStatus
  - LoanPurpose

outlier_remove_col:
  - Age
  - AnnualIncome
  - CreditScore
  - Experience
  - LoanAmount
  - LoanDuration
  - NumberOfDependents
  - MonthlyDebtPayments
  - CreditCardUtilizationRate
  - NumberOfOpenCreditLines
  - NumberOfCreditInquiries
  - DebtToIncomeRatio
  - PaymentHistory
  - LengthOfCreditHistory
  - SavingsAccountBalance
  - CheckingAccountBalance
  - TotalAssets
  - TotalLiabilities
  - MonthlyIncome
  - UtilityBillsPaymentHistory
  - JobTenure
  - NetWorth
  - BaseInterestRate
  - InterestRate
  - MonthlyLoanPayment
  - TotalDebtToIncomeRatio
